### ISSUE TITLE
Occasional crash

### ISSUE THREAD

**Issue by otta8634** [LyQuid12/discord-rpc#4]
Sometimes when `RPC.set_activity` is called, the script crashes with error
```
    if output['evt'] == "ERROR":
KeyError: 'evt'
```
Adding debug print for RPC.output, the error is
```py
{'code': 1003, 'message': 'data size does not match what was received'}
```
Seems to happen regardless of what the activity is set to.

**Comment by LyQuid12** [comment]
If you already open ticket on Discord, you cannot open issue with same case/topic. It will make me confused where to response first. This issue will be closed and re-open again until i find the solutions.

**Comment by otta8634** [comment]
Reopen
