### ISSUE TITLE
Occasional crash

### ISSUE THREAD

**Issue by otta8634** [LyQuid12/Discord-RPC#6]
Copy of #4 since @LyQuid12 won't reopen it.

Sometimes when RPC.set_activity is called, the script crashes with error
```py
    if output['evt'] == "ERROR":
KeyError: 'evt'
```
Adding debug print for RPC.output, the error is
```py
{'code': 1003, 'message': 'data size does not match what was received'}
```
Seems to happen regardless of what the activity is set to.

**Comment by Pukimaa** [comment]
What is your code that implements discord-rpc?
